### PR TITLE
make super(..) call compatible with python < 3

### PR DESCRIPTION
**Pull request by tmmorin**

### CODE REVIEW

**Comment by tmmorin** [comment]
Without that, the result of "pip install beagle" is a bit frustrating. :)

**Comment by dhellmann** [comment]
I only intended for beagle to support Python 3. Let me give it some thought. There may be other changes we need to support Python 2.

**Comment by tmmorin** [comment]
With this change a "beagle search xxx" work fine, I didn't try anything else.

Supporting python 3 only would be fine though, with only one thing that hurts: would there be a way to avoid pip to let me install on python2 something that doesn't support it ? or having beagle itself refuse to start under python2 ?

**Comment by dhellmann** [comment]
You would need to run a copy of pip installed for python 3. I usually run pip3 or "python3 -m pip" to ensure I get the one I want.

**Comment by tmmorin** [comment]
"pip3 install beagle" works without worry on my platform, but this wasn't my point which was that I would be glad to have pip running under python 2 have some way of refusing to install a package not supporting python2 (or at least warning me)

**Comment by dhellmann** [comment]
Oh, sorry, I misunderstood what you were asking. I am not aware of any way for pip to preemptively warn or error out about that situation.

**Comment by dhellmann** [comment]
Now that python 2 is officially deprecated upstream, I'm going to close this PR.

**Pull request closed without merging**
