### PR TITLE
modernize beagle environment

### PR DESCRIPTION
**Pull request by 4383**
- remove travis
- introduce github workflow
- upgrade supported versions of Python
- propose to use OIDC and trusted publishers (https://docs.pypi.org/trusted-publishers/) to publish from github jobs

### CODE REVIEW

**Comment by 4383** [comment]
@dhellmann o/ I'm not granted on pypi to add trusted publishers for beagle, do you mind adding it for us?

**Comment by dhellmann** [comment]
@4383 , I made you an owner on pypi.org, so you should now have permission.

**Comment by 4383** [comment]
Thank you

**Comment by 4383** [comment]
- github actions are running successfully
- pypi trusted publishers are now configured

Let's merge this patch

**Comment by 4383** [comment]
version 0.4.0 is now out https://pypi.org/project/beagle/0.4.0/

**Pull request merged**
